from pathlib import Path
import argparse
import ast
import numpy as np
import pandas as pd


def parse_marker_cell(cell):
    """
    Parse a marker cell from a marker database CSV.
    Args:  
        cell (str): String representation of a list of markers. [('PROT1', freq, pval), ('PROT2', freq, pval), ...]
    Returns:
        list (str): List of protein names.
    """
    if pd.isna(cell):
        return []
    return [x[0] for x in ast.literal_eval(cell)] 


def calculate_sample_quantiles(values, q2=0.5, q3=0.75, missing_at_random=True):
    """
    Calculate q2 and q3 for a 1D array of protein values from one sample.
    Args:
        values (array-like): 1D array of protein values for one sample.
        q2 (float): Quantile for median (default: 0.5).
        q3 (float): Quantile for upper quartile (default: 0.75).
        missing_at_random (bool): If True, zeros in proteomics data are treated as missing and excluded from quantile calculations.
    Returns:
        tuple: (q2_value, q3_value) where q2_value is the calculated q2 quantile and q3_value is the calculated q3 quantile. 
            If there are no valid values after filtering, both will be np.nan.
    """
    values = np.asarray(values, dtype=float)

    if missing_at_random:
        values = values[values != 0]

    if len(values) == 0:
        return np.nan, np.nan

    return np.quantile(values, q2), np.quantile(values, q3)


def calculate_d_values(
    marker_df,
    proteomics_df,
    q2=0.5,
    q3=0.75,
    missing_at_random=True,
    min_markers=4,
):
    """
    Calculate D values for each gene across samples.
    Args:
        marker_df (pd.DataFrame): DataFrame with gene markers, indexed by gene and containing columns 'marker_nes' and 'marker_ess' 
            with string representations of marker lists (e.g. "[('PROT1', freq, pval), ('PROT2', freq, pval), ...]").   
        proteomics_df (pd.DataFrame): DataFrame with proteomics data, indexed by sample and with protein names as columns.
        q2 (float): Quantile for median (default: 0.5).             
        q3 (float): Quantile for upper quartile (default: 0.75).
        missing_at_random (bool): If True, zeros in proteomics data are treated as missing and excluded from quantile calculations.
        min_markers (int): Minimum number of NES or ESS markers required for a gene to be included in D-value calculation (default: 4). If a gene has fewer than this number of markers, it will be skipped.
     Returns:       
        pd.DataFrame: DataFrame of D values with genes as rows and samples as columns.
    """
    d_value_df = pd.DataFrame(index=marker_df.index, columns=proteomics_df.index, dtype=float)

    for gene in marker_df.index:
        nes_names = parse_marker_cell(marker_df.loc[gene, "marker_nes"])
        ess_names = parse_marker_cell(marker_df.loc[gene, "marker_ess"])

        # Filter markers to those present in proteomics data
        nes_names = [p for p in nes_names if p in proteomics_df.columns]
        ess_names = [p for p in ess_names if p in proteomics_df.columns]

        # Skip genes that do not have enough NES or ESS markers after filtering to those present in proteomics data
        if len(nes_names) < min_markers or len(ess_names) < min_markers:
            print(f"{gene}: does not have enough NES or ESS markers.")
            continue

        #Skip genes with empty rows after filtering
        if len(nes_names) == 0 or len(ess_names) == 0:
            print(f"{gene}: no valid NES or ESS markers after filtering.")
            continue

        temp_nes_df = proteomics_df.loc[:, nes_names]
        temp_ess_df = proteomics_df.loc[:, ess_names]

        d_values = []
        for sample in proteomics_df.index:
            nes_q2, nes_q3 = calculate_sample_quantiles(
                temp_nes_df.loc[sample, :].values,
                q2=q2,
                q3=q3,
                missing_at_random=missing_at_random,
            )
            ess_q2, ess_q3 = calculate_sample_quantiles(
                temp_ess_df.loc[sample, :].values,
                q2=q2,
                q3=q3,
                missing_at_random=missing_at_random,
            )

            d_value = (ess_q2 - nes_q2) + (ess_q3 - nes_q3)
            d_values.append(d_value)

        d_value_df.loc[gene, :] = d_values

    return d_value_df


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--markers",
        required=True,
        help="Path to EMGD marker CSV generated by 03_generate_emgd_markers.py",
    )
    parser.add_argument(
        "--proteomics",
        required=True,
        help="Path to proteomics CSV with samples on rows and proteins on columns",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to output D-value CSV",
    )
    parser.add_argument(
        "--q2",
        type=float,
        default=0.5,
        help="Lower quantile term used in D-value calculation (default: 0.5)",
    )
    parser.add_argument(
        "--q3",
        type=float,
        default=0.75,
        help="Upper quantile term used in D-value calculation (default: 0.75)",
    )
    parser.add_argument(
        "--missing-at-random",
        action="store_true",
        help="Treat zeros as missing values and exclude them from quantile calculations",
    )
    parser.add_argument(
        "--min-markers",
        type=int,
        default=4,
        help="Minimum number of markers required per group before fallback substitution",
    )

    args = parser.parse_args()

    marker_df = pd.read_csv(args.markers, index_col=0)
    proteomics_df = pd.read_csv(args.proteomics, index_col=0)

    required_cols = {"marker_nes", "marker_ess"}
    missing_cols = required_cols.difference(marker_df.columns)
    if missing_cols:
        raise ValueError(
            f"Marker file is missing required columns: {sorted(missing_cols)}"
        )

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    d_value_df = calculate_d_values(
        marker_df=marker_df,
        proteomics_df=proteomics_df,
        q2=args.q2,
        q3=args.q3,
        missing_at_random=args.missing_at_random,
        min_markers=args.min_markers,
    )

    d_value_df.to_csv(output_path)
    print(f"Saved D-value matrix to: {output_path}")


if __name__ == "__main__":
    main()